version: '2'
services:
  lein:
    build: ./docker/arm
    container_name: lein
    restart: always
    volumes:
     - $PWD:/data
     - ~/.m2:/root/.m2
    environment:
      CONFIG: <YOUR CONFIG FILE PATH>
