version: '2'
services:
  esunconsulting:
    build: ./docker/x86
    container_name: esunconsulting
    restart: always
    volumes:
     - $PWD:/data
     - ~/.m2:/root/.m2
    environment:
      CONFIG: <YOUR CONFIG FILE PATH>
